### ISSUE TITLE
Seg Fault Non-connected cities

### ISSUE THREAD

**Issue by jaha6145** [trtr3104/Tran_CSCI2270_FinalProject#1]
When trying to find shortest distance between two cities which are not directly or indirectly connect, a segmentation fault occurs.

**Comment by trtr3104** [comment]
Again, I am not sure where you are getting this problem. I have attached an example. So from the picture, you can see that Yakima and New York is not connected.
![untitled](https://cloud.githubusercontent.com/assets/18508346/14906683/7636f196-0d7b-11e6-9269-80b61672b2ff.png)

If you still have this problem, please let me know and attach a picture.

**Comment by jaha6145** [comment]
Here is what I see. I will update you after the project is recloned and run.
<img width="364" alt="tran_option_3" src="https://cloud.githubusercontent.com/assets/18423213/14925747/2e9fea8c-0e06-11e6-9f3a-708b87e6b749.png">

**Comment by trtr3104** [comment]
This is what I got from the same inputs. 
![untitled](https://cloud.githubusercontent.com/assets/18508346/14940790/875d0196-0f41-11e6-80b7-e633e991747a.png)

It might be that you are using a different input file? Make sure to use the cities.txt in the FinalProject folder in my repo, not the one outside with the README file. I'm sorry if I didn't make that clear.

**Comment by jaha6145** [comment]
Everything seems to work seamlessly now, great work!
