### ISSUE TITLE
Avoid Toll feature 

### ISSUE THREAD

**Issue by jaha6145** [trtr3104/Tran_CSCI2270_FinalProject#2]
Seems like a nice feature but, does Avoid Toll, (#6 on menu) do anything but return to menu? When/how should this be used?

**Comment by trtr3104** [comment]
So if you look at the input file, for each edge (road), there is a distance, the speed limit, and whether it is a toll road or not (0 or 1). So the avoid toll feature is a On/Off switch to either take the toll road to the other city or to avoid toll.

**Comment by jaha6145** [comment]
Okay, that's a good idea! I just wasn't clear on that.

**Comment by jaha6145** [comment]
Works great, I like the On/Off print.
