### ISSUE TITLE
Delete City Not Working

### ISSUE THREAD

**Issue by jaha6145** [trtr3104/Tran_CSCI2270_FinalProject#4]
Menu item 8, like 7, doesn't not seem to be functioning. It asks for a city and returns the menu. When printing all, the city is still there and is still accounted for in other features such as shortest distance, etc.

**Comment by trtr3104** [comment]
Yes I just noticed that the delete city function needs a little tweak. It does delete the city that is asked, but then it also changes the edges and connections to other cities. I will fix that soon.

**Comment by jaha6145** [comment]
Nice fix!
