### ISSUE TITLE
Changed Project?

### ISSUE THREAD

**Issue by jaha6145** [trtr3104/Tran_CSCI2270_FinalProject#5]
Is this a different project? I tried to fork and clone it to my VM and it seems to be completely changed. This seems to be reflected in the repository as well. I thought I may have ended up at the wrong address but the open issues are still here, as part of this repository.

**Comment by trtr3104** [comment]
Yes I am sorry I am facing a technical difficulty. I meant to clone another person's project so I can evaluate and somehow I replaced their project on my repo. I am going to get it fixed today, I will let you know when it has been fixed. I apologize for the confusion.

**Comment by trtr3104** [comment]
I just fixed my problem. I apologize for the delay.
